exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions:
      - jpg
      - jpeg
      - png
      names: []

filesystem:
  firmware_folder: bios
  roms_folder: roms

system:
  platforms:
    3DS: 3ds
    DS: nds
    Flash: browser
    GameBoy: gb
    GameBoyAdvance: gba
    GameBoyColor: gbc
    GameCube: ngc
    N64: n64
    PS: psx
    PS2: ps2
    PS3: ps3
    PSP: psp
    PSVita: psvita
    SegaGenesis: genesis
    Switch: switch
    Wii: wii
    Windows: win
    XBox: xbox
    XBox360: xbox360
  versions: {}

# Metadata priority during scans
scan:
 priority:
   metadata: # Top-level metadata source priority
     - "igdb" # IGDB
     - "ra" # RetroAchievements
     - "hasheous" # Hasheous
     - "flashpoint" # Flashpoint Project
     - "hltb" # HowLongToBeat
     - "ss" # Screenscraper
   artwork: # Cover art and screenshots
     - "igdb" # IGDB
     - "ra" # RetroAchievements
     - "hasheous" # Hasheous
     - "flashpoint" # Flashpoint Project
     - "hltb" # HowLongToBeat
     - "ss" # Screenscraper
   region: # Cover art and game title (only used by Screenscraper)
     - "eu"
     - "us"
     - "wor"
     - "ss"
     - "jp"
   language: # Cover art and game title (only used by Screenscraper)
     - "en"
